# Generated by Django 4.2.11 on 2026-08-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biotop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kolor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150)),
                ('nazwa_lacinska', models.CharField(blank=True, max_length=150)),
                ('dlugosc_ciala_min', models.FloatField(help_text='cm')),
                ('dlugosc_ciala_max', models.FloatField(help_text='cm')),
                ('rozpietosc_skrzydel_min', models.FloatField(help_text='cm')),
                ('rozpietosc_skrzydel_max', models.FloatField(help_text='cm')),
                ('miesiac_od', models.PositiveSmallIntegerField(help_text='1-12')),
                ('miesiac_do', models.PositiveSmallIntegerField(help_text='1-12')),
                ('biotopy', models.ManyToManyField(related_name='gatunki', to='birds.biotop')),
                ('kolory', models.ManyToManyField(related_name='gatunki', to='birds.kolor')),
            ],
        ),
    ]
