# Generated by Django 4.2.11 on 2026-08-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatunek',
            name='nazwa_lacinska',
        ),
    ]
